---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: webcontent01
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: web-port
  selector:
    app: webcontent01